OrcidProfilePlugin.inc.php

whitespace changes

---

README.md

Answers the questions I had, anyway.

Clean up README, clarify installation instructions.

---

locale/fi_FI/emailTemplates.xml
locale/fi_FI/locale.xml

@mtub Finnish locale for orcidProfile

Finnish locale

---

OrcidProfilePlugin.inc.php
pages/OrcidHandler.inc.php

See https://forum.pkp.sfu.ca/t/orcid-id-not-retrieved/32196
ORCID 2.x moves fetching names and emails into two separate endpoints: "person" and "email".

Update for 2.0 endpoints "person" and "email"

---

locale/cs_CZ/emailTemplates.xml
locale/cs_CZ/locale.xml

files received from Jiri
related to pkp/pkp-lib#2605

new locale: cs_CZ

---

locale/da_DK/emailTemplates.xml
locale/da_DK/locale.xml

pkp/pkp-lib#2869 
from Niels Erik

pkp/pkp-lib#2869 added da_DK Danish locale

---

locale/en_US/locale.xml
locale/it_IT/locale.xml

it_IT locale

---

locale/de_DE/locale.xml
locale/en_US/locale.xml

de_DE locale update + en_US locale update

---

locale/fr_CA/emailTemplates.xml
locale/fr_CA/locale.xml

two new locale files for plugin orcidProfile

locale fr-ca

---

locale/pt_PT/locale.xml

I think I am not doing this the right way in my copy. Will have a lot of work setting all submodules origin to the official repositories :)

Added PT Locale

---

pages/OrcidHandler.inc.php

s. https://github.com/pkp/pkp-lib/issues/2958

given and family name

---

locale/es_ES/emailTemplates.xml
locale/es_ES/locale.xml

received by email from @marcbria

es_ES locale update

---

locale/tr_TR/emailTemplates.xml
locale/tr_TR/locale.xml

* this is for pkp/pkp-lib#4005

tr_TR locale update

---

OrcidProfileSettingsForm.inc.php

Plugin follow-up from pkp/pkp-lib#3578.

---

locale/it_IT/emailTemplates.xml
locale/it_IT/locale.xml

Update of it_IT

---

locale/nl_NL/emailTemplates.xml
locale/nl_NL/locale.xml

pkp/pkp-lib#4503 updated nl_NL locale

---

locale/el_GR/emailTemplates.xml
locale/el_GR/locale.xml

Update translated locales for Greek language

el_GR locale updated

---

OrcidProfilePlugin.inc.php
templates/settingsForm.tpl

pkp/pkp-lib#4998: Correct optional mail sending variable name

---

locale/fi_FI/locale.xml

@asmecher fi locale for 3.1.2 version of the plugin. Will do an update on master soon.

Fi locale for orcidProfile stable-3_1_2

---

locale/pt_BR/emailTemplates.xml
locale/pt_BR/locale.xml

Added pt_BR translation

---

locale/fr_CA/emailTemplates.xml
locale/fr_CA/locale.xml

@asmecher This update could also be integrated (copied) to branch `stable-3_1_2` if you deem this relevant.
Regarding issue https://github.com/pkp/pkp-lib/issues/5007, I have decided, while waiting for the fix in the English version, to base my translation on something like "This journal is collecting your ORCID iD so we can integrate your ORCID data with your user and author profile in OJS." as shown here: https://github.com/BibNumUMontreal/orcidProfile/blob/2d92217b9ef9dcf28a937d9e375e4d40eca97c21/locale/fr_CA/locale.xml#L61

Updated fr_CA locale

---

locale/fr_CA/emailTemplates.xml

As suggested in https://github.com/pkp/orcidProfile/pull/78#issuecomment-550385715

Updated fr_CA emailTemplates.xml

---

locale/bg_BG/emailTemplates.xml
locale/bg_BG/locale.po

Adding Bulgarian locale

---

README.md

See https://forum.pkp.sfu.ca/t/site-wide-configuration-of-orcid-profile-plugin/58140

Add link to PKP DOCS in README.md

---

version.xml

Release 1.1.2.1

---

OrcidProfilePlugin.inc.php

ORCID Icon Missing for 1st Author

Orcid Icon fix by @rkhalikov

---

OrcidProfilePlugin.inc.php

Attempt to fix the following issue
https://forum.pkp.sfu.ca/t/ojs-3-2-0-3-orcid-400-bad-request-invalid-json/60587/3

Language Handling enhancement

---

OrcidProfilePlugin.inc.php
pages/OrcidHandler.inc.php

* Submission URL update for multiple versions
* Author name fixes
* Code Consolidation

Multiple fixes : see documentation

---

templates/orcidProfile.tpl

https://github.com/pkp/orcidProfile/issues/142

When using the sandbox API, the ORCID validator can't validate

---

OrcidProfilePlugin.inc.php
templates/orcidProfile.tpl

https://github.com/pkp/orcidProfile/issues/171

Support API Version 3.0  - work create/update

---

OrcidProfilePlugin.inc.php
OrcidProfileSettingsForm.inc.php
README.md
classes/OrcidValidator.inc.php
classes/form/OrcidProfileSettingsForm.inc.php
classes/form/OrcidProfileStatusForm.inc.php
index.php
locale/en_US/locale.po
pages/OrcidHandler.inc.php
templates/settingsForm.tpl
templates/statusForm.tpl

**Issues**
- https://github.com/pkp/orcidProfile/issues/177

orcidProfile#177 ORCID plugin should not function without credentials 

---

.travis.yml
OrcidProfilePlugin.inc.php
classes/OrcidValidator.inc.php
classes/form/OrcidProfileSettingsForm.inc.php
classes/form/OrcidProfileStatusForm.inc.php
index.php
locale/en_US/locale.po
templates/orcidProfile.tpl
templates/settingsForm.tpl
templates/statusForm.tpl
version.xml

**Issues**
- https://github.com/pkp/orcidProfile/issues/177

orcidProfile#177 ORCID plugin should not function without credentials

---

OrcidProfilePlugin.inc.php
classes/form/OrcidProfileSettingsForm.inc.php
classes/form/OrcidProfileStatusForm.inc.php
cypress/tests/functional/02-Orcid-API.spec.js
locale/en_US/locale.po
pages/OrcidHandler.inc.php
templates/settingsForm.tpl

Updates Orcid reviewer credits using OJS reviewer confirmations.
Specification
#181

Reviewer credits

---

classes/form/OrcidProfileSettingsForm.inc.php

https://github.com/pkp/orcidProfile/issues/181

Differentiate OPS for reviewer support

---

OrcidProfilePlugin.inc.php
pages/OrcidHandler.inc.php

https://github.com/pkp/orcidProfile/issues/113

orcidProfile writes empty URI after failed auth

---

version.xml

Changed the version from 1.1.2.x to -> 1.1.3.0

Version bump for conflict resolution between OJS 3.2 and OJS 3.3

---

OrcidProfilePlugin.inc.php

https://forum.pkp.sfu.ca/t/ojs-3-3-0-7-orcid-plugin-error-with-handleeditoraction-method/72883

Bugfix: Add missing function handleEditorAction

---

locale/de_DE/locale.po

Changed Eireichung to Einreichung. Eireichung sounds more cute, though.

Fixed typo. 

---

OrcidProfilePlugin.inc.php
locale/en_US/locale.po
pages/OrcidHandler.inc.php
templates/orcidVerify.tpl

- https://github.com/pkp/orcidProfile/issues/113
- https://github.com/pkp/orcidProfile/issues/208

#pkp/orcidProfile/208 Restrict registartion to only journal contexts

---

OrcidProfilePlugin.inc.php

pkp/orcidProfile#211 Restrict registartion to only journal contexts

---

pages/OrcidHandler.inc.php

Issue
https://github.com/pkp/orcidProfile/issues/217

pkp/orcidProfile#217 Orcid Code string validation error

---

OrcidProfilePlugin.inc.php

This PR aims to provide support for pkp/pkp-lib#2564

pkp/pkp-lib#2564 Added functionality to strip HTML tags from submission title

---

OrcidProfilePlugin.inc.php

- https://github.com/pkp/orcidProfile/issues/235#
-

pkp/orcidProfile#235 OrcidProfile does not include the prefix

---

OrcidProfilePlugin.inc.php
pages/OrcidHandler.inc.php

- https://github.com/pkp/orcidProfile/issues/226

Add support for editing the Orcid after publication 

---

OrcidProfilePlugin.inc.php

- https://github.com/pkp/orcidProfile/issues/233

Check whether the member API is enabled before sending thanking reviewer

---

OrcidProfilePlugin.php

Issue
- https://github.com/pkp/orcidProfile/issues/249

orcidProfile#249 Temporary disabling  submission form hook to avoid error in the plugin

---

OrcidProfilePlugin.inc.php

https://github.com/pkp/orcidProfile/issues/149

orcidProfile#149 Detect duplicate Authors

---

OrcidProfilePlugin.php
locale/en/locale.po

- https://github.com/pkp/orcidProfile/issues/119

pkp/orcidProfile#119 Detected unauthenticated ORCiDs

---

OrcidProfilePlugin.inc.php

- https://github.com/pkp/orcidProfile/issues/258

pkp/orcidProfile#258 send DOI as publication url to orcid api

---

OrcidProfilePlugin.inc.php

-  https://github.com/pkp/orcidProfile/issues/262

https://github.com/pkp/orcidProfile/issues/262 Validate member api only for authenticaed orcids

---

OrcidProfilePlugin.inc.php
pages/OrcidHandler.inc.php
templates/orcidProfile.tpl

- https://github.com/pkp/orcidProfile/issues/266

Remove Orcid Username and id fetch from register from

---

OrcidProfilePlugin.inc.php

- https://github.com/pkp/orcidProfile/issues/271

pkp/orcidProfile#271 Remove the orcidToken previously rendered in publishing API

---

OrcidProfilePlugin.inc.php
pages/OrcidHandler.inc.php

s. https://github.com/pkp/orcidProfile/issues/281

pkp/orcidProfile#281 use new public API URL, enable API URL redirection

---

OrcidProfileHandler.php
OrcidProfilePlugin.php

s. https://github.com/pkp/orcidProfile/issues/281

pkp/orcidProfile#218 use new public API URL, enable URL redirection

---

OrcidProfilePlugin.inc.php

- https://github.com/pkp/orcidProfile/issues/281

orcidProfile#281 Add new Redirection API URL for public sandbox

---

OrcidProfilePlugin.inc.php
version.xml

s. https://github.com/pkp/orcidProfile/issues/281

pkp/orcidProfile#281 consider old API URL in plugin settings and update version

---

OrcidProfilePlugin.inc.php

- https://github.com/pkp/orcidProfile/issues/281

consider old API URL in plugin settings

---

OrcidProfileHandler.php
OrcidProfilePlugin.php

pkp/pkp-lib#9296 Sandbox settings
